<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2023/blob/main/HouseHolder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import scipy as sp
np.set_printoptions(precision=5, linewidth=200)

In [ ]:
rnd=np.random.RandomState(123)
N=5
A = rnd.normal(size=(N,N))
I=np.eye(N)

In [ ]:
A

array([[-1.08563,  0.99735,  0.28298, -1.50629, -0.5786 ],
       [ 1.65144, -2.42668, -0.42891,  1.26594, -0.86674],
       [-0.67889, -0.09471,  1.49139, -0.6389 , -0.44398],
       [-0.43435,  2.20593,  2.18679,  1.00405,  0.38619],
       [ 0.73737,  1.49073, -0.93583,  1.17583, -1.25388]])

In [ ]:
def householder(u,k):
    e=np.zeros_like(u)
    e[k]=np.linalg.norm(u[k:])
    v = u - e
    v[:k]=0
    v=(v/np.linalg.norm(v)).reshape(-1,1)
    return np.eye(e.size)-2*(v@v.T)

In [ ]:
h=householder(A[:,0],0)
M1= h @ A
M1

array([[ 2.25812e+00, -2.16326e+00, -1.62432e+00,  2.03291e+00, -7.05951e-01],
       [-6.88810e-17, -8.65696e-01,  5.13078e-01, -4.82032e-01, -8.03844e-01],
       [-6.80798e-17, -7.36411e-01,  1.10415e+00,  7.96672e-02, -4.69838e-01],
       [-2.94837e-17,  1.79537e+00,  1.93903e+00,  1.46379e+00,  3.69644e-01],
       [-9.50643e-17,  2.18771e+00, -5.15234e-01,  3.95359e-01, -1.22580e+00]])

In [ ]:
h=householder(M1[0,:],1)
M2=M1@ h
M2

array([[ 2.25812e+00,  3.45676e+00, -2.02065e-18, -6.24837e-17, -7.54941e-17],
       [-6.88810e-17,  1.81346e-01,  8.15699e-01, -8.60775e-01, -6.72321e-01],
       [-6.80798e-17,  8.48179e-02,  1.34150e+00, -2.17393e-01, -3.66681e-01],
       [-2.94837e-17, -1.24933e+00,  1.05904e+00,  2.56514e+00, -1.28128e-02],
       [-9.50643e-17, -6.44130e-01, -1.33370e+00,  1.41971e+00, -1.58152e+00]])

In [ ]:
h=householder(M2[:,1],1)
M3= h @ M2
M3

array([[ 2.25812e+00,  3.45676e+00, -2.02065e-18, -6.24837e-17, -7.54941e-17],
       [ 5.62075e-17,  1.41979e+00, -1.42488e-01, -3.02419e+00,  6.20995e-01],
       [-7.66467e-17, -1.07091e-17,  1.40713e+00, -6.92262e-02, -4.55256e-01],
       [ 9.67041e-17,  2.17830e-16,  9.24289e-02,  3.82711e-01,  1.29187e+00],
       [-3.00045e-17,  8.35481e-17, -1.83207e+00,  2.94495e-01, -9.08849e-01]])

In [ ]:
h=householder(M3[1,:],2)
M4=M3@ h
M4

array([[ 2.25812e+00,  3.45676e+00,  4.60655e-17, -1.75041e-17, -8.47303e-17],
       [ 5.62075e-17,  1.41979e+00,  3.09058e+00, -1.39481e-16,  1.65860e-17],
       [-7.66467e-17, -1.07091e-17, -8.86102e-02, -1.46833e+00, -1.67961e-01],
       [ 9.67041e-17,  2.17830e-16, -1.19174e-01,  1.84778e-01,  1.33251e+00],
       [-3.00045e-17,  8.35481e-17, -3.86320e-01,  1.64684e+00, -1.18654e+00]])

In [ ]:
h=householder(M4[:,2],2)
M5= h @ M4
M5

array([[ 2.25812e+00,  3.45676e+00,  4.60655e-17, -1.75041e-17, -8.47303e-17],
       [ 5.62075e-17,  1.41979e+00,  3.09058e+00, -1.39481e-16,  1.65860e-17],
       [ 1.65709e-17, -1.38415e-16,  4.13880e-01, -1.27602e+00,  7.59799e-01],
       [ 1.18812e-16,  1.87542e-16, -3.66744e-17,  2.30389e-01,  1.55255e+00],
       [ 4.16621e-17, -1.46331e-17, -1.21530e-16,  1.79469e+00, -4.73271e-01]])

In [ ]:
h=householder(M5[2,:],3)
M6=M5@ h
M6

array([[ 2.25812e+00,  3.45676e+00,  4.60655e-17, -2.83096e-17, -8.17568e-17],
       [ 5.62075e-17,  1.41979e+00,  3.09058e+00,  1.28329e-16, -5.71097e-17],
       [ 1.65709e-17, -1.38415e-16,  4.13880e-01,  1.48510e+00,  2.54875e-16],
       [ 1.18812e-16,  1.87542e-16, -3.66744e-17,  5.96355e-01,  1.45184e+00],
       [ 4.16621e-17, -1.46331e-17, -1.21530e-16, -1.78416e+00,  5.11552e-01]])

In [ ]:
h=householder(M6[:,3],3)
M7= h @ M6
M7

array([[ 2.25812e+00,  3.45676e+00,  4.60655e-17, -2.83096e-17, -8.17568e-17],
       [ 5.62075e-17,  1.41979e+00,  3.09058e+00,  1.28329e-16, -5.71097e-17],
       [ 1.65709e-17, -1.38415e-16,  4.13880e-01,  1.48510e+00,  2.54875e-16],
       [-1.84854e-18,  7.33312e-17,  1.03635e-16,  1.88119e+00, -2.49190e-02],
       [-1.25891e-16, -1.73231e-16,  7.33090e-17,  2.06151e-16, -1.53913e+00]])

In [ ]:
M7[np.abs(M7)<1e-15]=0
M7

array([[ 2.25812,  3.45676,  0.     ,  0.     ,  0.     ],
       [ 0.     ,  1.41979,  3.09058,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.41388,  1.4851 ,  0.     ],
       [ 0.     ,  0.     ,  0.     ,  1.88119, -0.02492],
       [ 0.     ,  0.     ,  0.     ,  0.     , -1.53913]])