<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2023/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import minimize

In [11]:
xdata = np.linspace(-1,1,20)
ydata = 2.*xdata+1.
ydata = np.random.normal(loc=ydata, scale = 0.1)

In [4]:
fig=make_subplots()
fig.add_scatter(x=xdata,y=ydata,mode='markers')
fig.update_layout(width=600,height=400,template='plotly_dark')

In [6]:
def sse(v):
    m,b = v
    return np.sum((m*xdata + b - ydata)**2)

In [8]:
minimize(sse, [0.,0.]).x

array([2.01349488, 0.98100763])

In [9]:
A=np.c_[xdata, np.ones_like(xdata)]

In [10]:
np.linalg.solve(A.T @ A, A.T @ ydata)

array([2.01349489, 0.98100764])

In [12]:
np.polyfit(xdata, ydata, 1)

array([2.03473558, 1.011895  ])