<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2023/blob/main/VLE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -N -q https://raw.githubusercontent.com/profteachkids/chetools/main/tools/che5.ipynb -O che5.ipynb
!pip install importnb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 kB 2.1 MB/s eta 0:00:00


In [2]:
from importnb import Notebook
with Notebook():
    from che5 import Props

import numpy as np
import jax
import jax.numpy as jnp

from scipy.optimize import root_scalar

In [23]:
p=Props(['Ethanol','Isopropanol','Water'])
z = jnp.array([1/3,1/3,1/3])

In [4]:
def bubblePy_ideal(x, T):
    Pi = x*p.Pvap(T)
    bubbleP = np.sum(Pi)
    return bubbleP, Pi/bubbleP

In [5]:
@jax.jit
def bubbleTy_ideal_eq(x, T, P):
    return jnp.sum(x*p.Pvap(T)/P) - 1.

bubbleTy_ideal_eq_gradT = jax.jit(jax.grad(bubbleTy_ideal_eq, 1))
bubbleTy_ideal_eq_grad2T = jax.jit(jax.grad(bubbleTy_ideal_eq_gradT, 1))



def bubbleTy_ideal(x, P):
    Tb = p.Tb(P)
    Tguess = jnp.sum(x*Tb)

    res = root_scalar(lambda T: bubbleTy_ideal_eq(x,T,P), x0=Tguess,
                fprime=lambda T: bubbleTy_ideal_eq_gradT(x,T,P),
                fprime2=lambda T: bubbleTy_ideal_eq_grad2T(x,T,P),
                      method='halley')
    if not(res.converged):
        print(res)

    return res.root

def dewPx_ideal(y, T):
    y_div_Psat = y/p.Pvap(T)
    dewP = 1./jnp.sum(y_div_Psat)
    return dewP, y_div_Psat*dewP

@jax.jit
def dewTx_ideal_eq(y, T, P):
    return jnp.sum(y*P/p.Pvap(T)) - 1.

dewTx_ideal_eq_gradT = jax.jit(jax.grad(dewTx_ideal_eq, 1))
dewTx_ideal_eq_grad2T = jax.jit(jax.grad(dewTx_ideal_eq_gradT, 1))

def dewTx_ideal(y, P):
    Tb = p.Tb(P)
    Tguess = jnp.sum(y*Tb)
    res = root_scalar(lambda T: dewTx_ideal_eq(y,T,P), x0=Tguess,
                fprime=lambda T: dewTx_ideal_eq_gradT(y,T,P),
                fprime2=lambda T: dewTx_ideal_eq_grad2T(y,T,P),
                      method='halley')
    if not(res.converged):
        print(res)

    return res.root

In [6]:
dewTx_ideal(z, 2e5)

Array(393.56318087, dtype=float64)

In [8]:
#NRTL Parameters: Tij = Aij + Bij/T + Cij * Ln(T) + Dij * T (T Deg K)

In [38]:
def NRTL(x, T):

    tau = p.NRTL_A + p.NRTL_B/T + p.NRTL_C*jnp.log(T) + p.NRTL_D*T
    G = jnp.exp(- p.NRTL_alpha*tau)
    tauG = tau*G

    # xG_einsum = np.einsum('k, ki -> i', x, G)
    # xtauG_einsum = np.einsum('k, ki -> i', x, tauG)
    xG = x @ G
    xtauG = x @ tauG
    xtauG_xG = xtauG / xG
    return np.exp(xtauG_xG +  x@  ((G * (tau - xtauG_xG))/xG).T)


In [51]:
def nGexRT(n, T):

    x = n/jnp.sum(n)

    tau = p.NRTL_A + p.NRTL_B/T + p.NRTL_C*jnp.log(T) + p.NRTL_D*T
    G = jnp.exp(- p.NRTL_alpha*tau)
    tauG = tau*G
    xG = x @ G
    xtauG = x @ tauG
    xtauG_xG = xtauG / xG

    return jnp.sum(x * xtauG_xG)


In [52]:
nGexRT(z, 373.15)

Array(0.26756071, dtype=float64)

In [53]:
lngamma=jax.grad(nGexRT, 0)

In [54]:
jnp.exp(lngamma(z,373.15))

Array([0.78910768, 0.87039728, 1.45594914], dtype=float64)

In [39]:
NRTL(z,373.15)

array([1.03118458, 1.13741164, 1.90259498])

In [41]:
p.NRTL_gamma(z,373.15)

Array([1.03118458, 1.13741164, 1.90259498], dtype=float64)